<?php

namespace Tests\Feature\Admin;

use App\Models\Order;
use App\Models\Package;
use App\Models\Role;
use App\Models\User;
use App\Models\UserSubscription;
use Database\Seeders\RolePermissionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Carbon\Carbon;

class SubscriptionAccessTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->seed(RolePermissionSeeder::class);

        // Seed default packages
        Package::create([
            'id' => 1,
            'name' => 'Basic',
            'price' => 100000,
            'invitation_quota' => 1,
            'duration_days' => 30,
            'status' => 'active',
        ]);
    }

    private function createOrderAndUser(string $email = 'user@example.com'): array
    {
        $order = Order::create([
            'customer_name' => 'Jane Client',
            'phone' => '08987654321',
            'email' => $email,
            'package_id' => 1,
            'quota' => 1,
            'price' => 100000,
            'status' => 'confirmed',
            'start_date' => Carbon::today()->toDateString(),
            'end_date' => Carbon::today()->addDays(30)->toDateString(),
        ]);

        $user = User::where('email', $email)->first();
        
        // Delete automatic subscription generated by the Order hook to allow manual configuration in specific tests
        UserSubscription::where('order_id', $order->id)->delete();

        return [$order, $user];
    }

    /**
     * User dengan langganan aktif dapat mengakses dashboard.
     */
    public function test_user_with_active_subscription_can_access_dashboard(): void
    {
        [$order, $user] = $this->createOrderAndUser('active@example.com');

        // Buat subscription aktif
        UserSubscription::create([
            'user_id' => $user->id,
            'order_id' => $order->id,
            'package_id' => 1,
            'start_date' => Carbon::today()->subDays(5)->toDateString(),
            'end_date' => Carbon::today()->addDays(25)->toDateString(),
            'status' => 'active',
        ]);

        $response = $this->actingAs($user)->get(route('admin.dashboard'));
        $response->assertStatus(200);
    }

    /**
     * User dengan langganan kedaluwarsa diarahkan ke /subscription-expired.
     */
    public function test_user_with_expired_subscription_is_redirected_to_expired_page(): void
    {
        [$order, $user] = $this->createOrderAndUser('expired@example.com');

        // Buat subscription kedaluwarsa
        UserSubscription::create([
            'user_id' => $user->id,
            'order_id' => $order->id,
            'package_id' => 1,
            'start_date' => Carbon::today()->subDays(35)->toDateString(),
            'end_date' => Carbon::today()->subDays(5)->toDateString(),
            'status' => 'active',
        ]);

        $response = $this->actingAs($user)->get(route('admin.dashboard'));
        $response->assertRedirect(route('subscription.expired'));
    }

    /**
     * User dengan langganan yang belum dimulai diarahkan ke /subscription-expired.
     */
    public function test_user_with_future_subscription_is_redirected_to_expired_page(): void
    {
        [$order, $user] = $this->createOrderAndUser('future@example.com');

        // Buat subscription baru mulai minggu depan
        UserSubscription::create([
            'user_id' => $user->id,
            'order_id' => $order->id,
            'package_id' => 1,
            'start_date' => Carbon::today()->addDays(7)->toDateString(),
            'end_date' => Carbon::today()->addDays(37)->toDateString(),
            'status' => 'active',
        ]);

        $response = $this->actingAs($user)->get(route('admin.dashboard'));
        $response->assertRedirect(route('subscription.expired'));
    }

    /**
     * Admin/Superadmin dapat mengakses dashboard meskipun tidak memiliki langganan.
     */
    public function test_admin_and_superadmin_can_access_dashboard_without_subscription(): void
    {
        // Admin
        $admin = User::factory()->create();
        $adminRole = Role::where('name', 'Admin')->first();
        $admin->roles()->sync([$adminRole->id]);

        $response = $this->actingAs($admin)->get(route('admin.dashboard'));
        $response->assertStatus(200);

        // Superadmin
        $superadmin = User::factory()->create();
        $superadminRole = Role::where('name', 'Superadmin')->first();
        $superadmin->roles()->sync([$superadminRole->id]);

        $response = $this->actingAs($superadmin)->get(route('admin.dashboard'));
        $response->assertStatus(200);
    }

    /**
     * Konfirmasi atau aktifkan pesanan otomatis membuat user dan subscription.
     */
    public function test_confirming_or_activating_order_automatically_resolves_user_and_subscription(): void
    {
        // Simpan order dengan status confirmed
        $order = Order::create([
            'customer_name' => 'Jane Client',
            'phone' => '08987654321',
            'email' => 'jane@example.com',
            'package_id' => 1,
            'quota' => 1,
            'price' => 100000,
            'status' => 'confirmed',
            'start_date' => Carbon::today()->toDateString(),
            'end_date' => Carbon::today()->addDays(30)->toDateString(),
        ]);

        // Assert user terbuat secara otomatis
        $this->assertDatabaseHas('users', [
            'email' => 'jane@example.com',
            'name' => 'Jane Client',
            'phone' => '08987654321',
            'status' => 'active',
        ]);

        $user = User::where('email', 'jane@example.com')->first();
        $this->assertNotNull($user);
        $this->assertTrue($user->hasRole('User'));

        // Assert order terhubung ke user
        $order->refresh();
        $this->assertEquals($user->id, $order->user_id);

        // Assert subscription terbuat secara otomatis
        $subscription = UserSubscription::where('order_id', $order->id)->first();
        $this->assertNotNull($subscription);
        $this->assertEquals($user->id, $subscription->user_id);
        $this->assertEquals($order->id, $subscription->order_id);
        $this->assertEquals(1, $subscription->package_id);
        $this->assertEquals(Carbon::today()->toDateString(), $subscription->start_date->toDateString());
        $this->assertEquals(Carbon::today()->addDays(30)->toDateString(), $subscription->end_date->toDateString());
        $this->assertEquals('active', $subscription->status);
    }
}
